services:
  db:
    image: postgres:17
    container_name: postgres-db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: task-manager-api
    restart: always

    depends_on:
      - db

    ports:
      - "3000:3000"

    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: taskdb

volumes:
  postgres-data: